server:
  port: 0
  error:
    include-message: always

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:portfolio
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
    show-sql: 'true'
    defer-datasource-initialization: 'true'